# docker-compose.yml
version: "3.8"

services:
  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: ${MONGODB_URI}
      PORT: ${PORT}

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
