version: "3.8"
services:
  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

environment:
  - MONGO_URI
  - PORT
volumes:
  mongo_data:


  
