version: "3.8"
services:
  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

    # still injects into process.env if you ever drop dotenv
    env_file:
      - backend/.env

    # this makes the file visible inside the container so dotenv can read it
    volumes:
      - ./backend/.env:/usr/src/app/.env:ro

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
