version: "3.8"

services:
  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - backend/.example.env        # ← relative path to your backend/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
