version: "3.8"

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - app-network

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
