name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.sha }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install deps
        run: npm ci

      - name: Lint & Test
        run: npm run lint && npm test

      - name: Log in to registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & push Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/backend:$TAG .
          docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/backend:$TAG


      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /path/to/backend
            echo "TAG=$TAG" > .env        # override tag in your .env if you like
            docker-compose pull
            docker-compose up -d
