on:
  push:        # fires on every push to main
  pull_request:

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    env: { TAG: ${{ github.sha }} }
    steps:
      # … checkout, install, lint/test …

      - name: Build Docker image
        run: |
          docker build \
            --file FRONTEND/Dockerfile \
            --tag ghcr.io/${{ secrets.DOCKER_USERNAME }}/frontend:$TAG \
            FRONTEND
      # … login, push …

      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.8
        with:
          script: |
            cd /path/to/your/project
            export TAG=$TAG
            docker-compose pull frontend
            docker-compose up -d frontend
