name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Lint & Test
        run: npm run lint && npm test

      - name: Log in to registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" \
            | docker login ghcr.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & push Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/backend:${TAG} .
          docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/backend:${TAG}

      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /path/to/backend
            echo "TAG=${TAG}" > .env
            docker-compose pull backend
            docker-compose up -d backend

