# .github/workflows/ci.yml

name: "CI/CD"

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: "CI: Install dependencies"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend deps
        run: npm ci
        working-directory: backend

      - name: Install frontend deps
        run: npm ci
        working-directory: frontend

  deploy:
    name: "🛡️ CD: Deploy to VM"
    needs: ci
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.8
        with:
          host:       ${{ secrets.SSH_HOST }}
          username:   ${{ secrets.SSH_USER }}
          key:        ${{ secrets.SSH_PRIVATE_KEY }}
          port:       ${{ secrets.SSH_PORT }}
          debug:      true
          script: |
            set -euxo pipefail
            cd "$HOME/new-app" || {
              git clone git@github.com:ShaheeraMalik/Crud-Mern-Stack.git "$HOME/new-app"
              cd "$HOME/new-app"
            }
            git fetch origin main
            git reset --hard origin/main

            export MONGODB_URI="${{ secrets.MONGODB_URI }}"
            export PORT="${{ secrets.PORT }}"

            docker compose down --remove-orphans || true
            sudo systemctl stop nginx || true
            docker ps -q --filter "publish=${PORT}" | xargs -r docker rm -f

            docker compose build --pull
            docker compose up -d
